# Generated by Django 3.0.6 on 2020-07-26 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Loan',
        ),
    ]
