# Generated by Django 3.0.6 on 2020-07-27 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_loan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gre_score', models.IntegerField()),
                ('toefl_Score', models.CharField(max_length=3)),
                ('university_rating', models.IntegerField()),
                ('sop', models.DecimalField(decimal_places=1, max_digits=2)),
                ('lop', models.DecimalField(decimal_places=1, max_digits=2)),
                ('cgpa', models.DecimalField(decimal_places=2, max_digits=3)),
                ('research', models.IntegerField()),
                ('result', models.DecimalField(decimal_places=8, max_digits=10)),
            ],
        ),
    ]
