# Generated by Django 3.0.6 on 2020-07-31 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_spam'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admission',
            old_name='toefl_Score',
            new_name='toefl_score',
        ),
    ]
