# Generated by Django 3.0.6 on 2020-08-04 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200731_0653'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('problem', models.CharField(max_length=100)),
                ('message', models.TextField(max_length=500)),
                ('datetime', models.DateTimeField()),
            ],
        ),
    ]
